### ISSUE TITLE
The "Explore the Ethereum Blockchain" is currently broken

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#1453] opened 2018-07-19 13:57 UTC
Seems that some breaking changes have happened in DAG API / IPLD land that went uncaught.

@vmx do you know what changed? Can you look into this?

**Comment by vmx** [comment] 2018-07-19 14:05
Please give instructions on how to reproduce.

**Comment by vmx** [comment] 2018-07-19 14:20
Oh, I guess you mean the example at `examples/explore-ethereum-blockchain`. I'll have a look.

**Comment by vmx** [comment] 2018-07-19 14:42
Works for me, here's what I did:

```
$ IPFS_PATH=/tmp/ethtest jsipfs init
initializing ipfs node at /tmp/ethtest
generating 2048-bit RSA keypair...done
peer identity: QmerPBKys7edagWswnSETLAqKgxHynttLdvMDXaxHQKgee
to get started, enter:

	jsipfs files cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme


$ IPFS_PATH=/tmp/ethtest ./load-eth-stuffs.sh
z43AaGEvwdfzjrCZ3Sq7DKxdDHrwoaPQDtqF4jfdkNEVTiqGVFW
z43AaGEywSDX5PUJcrn5GfZmb6FjisJyR7uahhWPk456f7k7LDA
z43AaGF42R2DXsU65bNnHRCypLPr9sg6D7CUws5raiqATVaB1jj
z45oqTS2AQ9SgyVa31LRGZgfibtdoPvP2miMNaXbDLLgD9MdAAr
z45oqTS8wZaNGU2eepKHRbXvmV93cKQbiL241RB3bRtMYZP8hNm
z45oqTS8wZaNGU2eepKHRbXvmV93cKQbiL241RB3bRtMYZP8hNm
z45oqTS4E1GeJujnKVJG3xSVnS64A8mMCWhKSkCWACNCeD95mtQ
z45oqTS4MnurEeEaanvFieeJDNHH3jGNk9NJEiyrwXwYQSWfxUB
z45oqTRwExySeMeivsU1Y9UdzWDp2mx71TtQhmTGzRaXCcsNujj
z45oqTRzb9a5xyvx5RbfSXH1K5jibyZ4AxnXyYReuLw7KU5veYw
$ IPFS_PATH=/tmp/ethtest jsipfs dag get z43AaGEvwdfzjrCZ3Sq7DKxdDHrwoaPQDtqF4jfdkNEVTiqGVFW/
=�{���"D�*��p�_�o!��-�K�p�;N,�M���]z���g����E�t�B�@ԓG,�gO���������j�qk���,O��T�+SA�~@!&�>i(
                                                                                           ��
�������,V�U���E���n[H�l��b/��c�!,c3��H.�^/g�v�l
                                               �{��Li�m
                                                       TղG,  ,r�|:�,0%,=	!,?�,X�)�,ethermine - US1,i�k^��ZC/ĘsQ[�7zu]�(t�7,�d�sn�
$ IPFS_PATH=/tmp/ethtest jsipfs dag get z43AaGEvwdfzjrCZ3Sq7DKxdDHrwoaPQDtqF4jfdkNEVTiqGVFW/parentHash
0x3dec047bc8e0dc2218449e2a0487ca70b95fb56f218d942d824b029f70893b4e
```

Hence I close this issue. @diasdavid If you don't think it works as expected, please provide details.

```

**Comment by diasdavid** [comment] 2018-07-19 16:56
@vmx check the experience described on https://github.com/ipfs/go-ipld-eth/blob/master/plugin/README.md

**Comment by vmx** [comment] 2018-07-20 09:57
@diasdavid Can you please provide more information? Did it work in the past? Which parts of the document you linked do you expect to work (e.g. there's not `dag put` in jsipfs yet)? What are the steps to reproduce?

**Comment by daviddias** [comment] 2019-10-02 09:15
> https://github.com/ipfs/js-ipfs/issues/1453#issuecomment-406301009

The first dag get returns a buffer, rather than a human readable json blob 

> (e.g. there's not dag put in jsipfs yet)?

Why not? What's missing to get it?

**Comment by achingbrain** [comment] 2019-10-02 09:27
> there's not dag put in jsipfs yet

I must be reading this wrong.  It's [here in core](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/dag.js#L11-L57) and [here in ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client/blob/master/src/dag/put.js).

**Comment by daviddias** [comment] 2019-10-02 15:00
@achingbrain it's not on the CLI, which is what go is using to showcase its demos.

**Comment by SgtPooki** [comment] 2023-05-26 18:27
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

FYI that we're removing the ethereum block from explore.ipld.io because it's not being served on IPFS anymore.. see https://github.com/ipld/explore.ipld.io/issues/74

If you have a good example of an ethereum block that we should be able to render on explore.ipld.io please open an issue in the ipfs/ipld-explorer-components repo.

**Closed by SgtPooki** 2023-05-26 18:27 UTC
Labels: kind/bug, status/ready, P1, ipld
