### ISSUE TITLE
pubsub.peers stays empty, but nodes are connected as swarm peers via webrtc-star (0.49.1) 

### ISSUE THREAD

**Issue by StationedInTheField** [ipfs/js-ipfs#3249] opened 2020-08-26 22:55 UTC
0.49.1
Chrome (most likely more):
PubSub

#### Description:
ipfs id and repo unique on browserwindow1
connect to remote webrtc-star (my own) on :80 from browserwindow1
```
let ipfsEmptyConfig = {
          repo: 'anon-repo-'+uuidv4(),
          config: {
            Addresses: {
              Swarm: [  "/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star" ]
               API: '',
              Gateway: ''
            },
          EXPERIMENTAL: {
               pubsub: true
             }
          }};

let node = await ipfs.create(ipfsEmptyConfig);
```
first browser gets 10 swarm peers
after peers are connected subscribe to topic
wait 5 seconds to 15 minutes...
ipfs id and repo unique on browserwindow2
connect to remote webrtc-star (my own) on :80 from browserwindow2
second browser gets 11 swarm peers (10+browserwindow1) 
after peers are connected subscribe to same topic as browserwindow1

#### Issue:
node.swarm.peers() includes browserwindow1 that is subscribed to the same topic but node.pubsub.peers() ends up empty.

Logically messages are not seen by the other party, but messages sent from the same tab are received in the pubsub subscription on that tab as new message, the windows/tabs stay disconnected. 

When stay connected and subscribe and try 2 minutes later, they are still swarm peers but not pubsub peers.

It's wild because I tested what I thought worked like this a few weeks ago and the instances had no problem finding each other. Is there possibly a limitation to the length of a topic name? or special characters? mine can be 128 characters+ and include "-" and hex.

**Comment by achingbrain** [comment] 2020-08-27 14:27
There's no practical limit on topic name length or content AFAIK - could you post a more complete example please?  Specifically how you are setting up the pubsub subscription & sending/receiving messages?

**Comment by StationedInTheField** [comment] 2020-08-27 14:54
Subscription:
```
node.pubsub.subscribe("test-----topic", async(message) => {
        console.log('New message!',message);
});
``` 
^^ This actually catches my own messages sent from:
```
node.pubsub.publish("test-----topic", msgData);
});
``` 
And if I do ```node.pubsub.ls()``` I get the topic(s) I'm subscribed to
But ```node.pubsub.peers()`` keeps giving me an empty Array even though window2 can see window1 as swarm peer

**Comment by StationedInTheField** [comment] 2020-08-31 16:07
So for now I just opted to downgrade to ^0.46 because it works with that version without any changes. Would be great to get some feedback on when this will be fixed! =)

**Comment by vasco-santos** [comment] 2020-09-03 16:43
I could not replicate this so far. @StationedInTheField do you have any code that I can test/debug available? If you could provide me a small code example that I could install and run in both browsers would be super helpful. Or a branch in `ngx-electron` with instructions to test if?
Another thing I noticed, are you doing `node.pubsub.peers()` or `node.pubsub.peers(topic)`?

**Comment by StationedInTheField** [comment] 2020-09-05 10:10
Give me two days, then I'll have finished 0.9.1 (a very light and the first actually usable version, the prior versions didn't allow custom channel trees, of my messenger) 

It works in the browser, so that's probably the best way to see where it's failing, probably easiest to just import that into stackblitz from the repo then. All it takes to break it is to change the ipfs version in the package.json from 0.46.1 to a later one.

**Comment by vasco-santos** [comment] 2020-09-05 13:58
@StationedInTheField sure, let me know when it is ready!

**Comment by StationedInTheField** [comment] 2020-09-07 10:37
@vasco-santos I just released it: https://github.com/QuestNetwork/quest-messenger-js

**Comment by vasco-santos** [comment] 2020-09-07 12:48
I cannot access the demo link. I am installing from github to try it locally now.
Can you just point me where is the pubsub related code and the flows that I should do in the web app once I start it?

**Comment by vasco-santos** [comment] 2020-09-07 13:25
I suspect that you had some version issue when you opened this issue thanks to the package-lock. Perhaps `libp2p-pubsub` version was not in line with what it should be 🤔 I tried to understand how to test using your project locally, but I could not do it without instructions.

I just pushed the example I tried out last week: https://github.com/vasco-santos/ipfs-browser-pubsub-example

I tried with `0.49.1` and also with the newest release `0.50.0` (with the new gossipsub 1.1) and everything seems to work (I used your topic example). Can you try my example / retry this in your project cleaning the package-locl

**Comment by StationedInTheField** [comment] 2020-09-07 13:44
It's propagated now and available at: https://gateway.pinata.cloud/ipfs/QmYDKkaCtwAG1obMezLS1RgNmke5CxjrtdRU4fdpgzMuP4/

I tried it on fresh Ubuntu machine and it worked, I gave instructions in https://github.com/QuestNetwork/quest-messenger-js#development - ```npm run inst``` removes the package-lock.json - I will try your example

**Comment by StationedInTheField** [comment] 2020-09-07 14:04
Yep using your example I was able to update the current development branch (0.9.2) to  0.50.1, it works fine and peers with other messengers running 0.9.1 with the 0.46.1 of ipfs

**Comment by StationedInTheField** [comment] 2020-09-07 14:04
Thanks!

**Comment by StationedInTheField** [comment] 2020-09-07 14:18
Works! Don't hesitate to point people in my direction who might be interested in helping me build the Matrix equivalent for IPFS with lots of advanced features (I have a background in image recognition and neural language processing and among other things I'm planning to add native suggestions to the messenger)

**Comment by StationedInTheField** [comment] 2020-09-07 14:19
Thanks again!

**Comment by vasco-santos** [comment] 2020-09-07 14:35
> Don't hesitate to point people in my direction who might be interested in helping me build the Matrix equivalent for IPFS with lots of advanced features (I have a background in image recognition and neural language processing and among other things I'm planning to add native suggestions to the messenger)

Got it 👌 

> Works! 

Closing this issue as the issue is solved 😄

**Closed by vasco-santos** 2020-09-07 14:35 UTC
Labels: kind/bug, need/author-input
