### ISSUE TITLE
Current situation regarding ipfs.add progress in browser?

### ISSUE THREAD

**Issue by christopheSeeka** [ipfs/js-ipfs#3214] opened 2020-08-06 05:21 UTC
Im implementing js-ipfs in my project where users will be able to add files up to 50mb.
I'm facing the known problem of the progress callback not responding in browser untill the file is completely added.
I searched a bit everywhere but didn't find any solution.

Its a bit difficult to imagine having users adding files and wait for a minute or more without any progress feedback.

What is the situation about this and what are the possible alternative to get a feedback on the add file?

**Comment by achingbrain** [comment] 2020-08-06 13:16
This is a duplicate of #2854

**Closed by achingbrain** 2020-08-06 13:16 UTC
Labels: need/triage
