### ISSUE TITLE
key/import returns HTTPError: file argument 'key' is required

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/js-ipfs#3535] opened 2021-02-07 12:14 UTC
#### Version information:
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4

#### Description:
There's an incompatibility with ipfs-http-client key import using pem and password resulting in an `HTTPError: file argument 'key' is required`

Steps to reproduce the error:

```
    const ipfsClient = require('ipfs-http-client')
    const ipfs = ipfsClient(await ipfsClient({
	url: __REMOTE_API_ADDRESS__, //Connect with go-ipfs node
	agent: ...
    })
    const key = await crypto.keys.generateKeyPair('rsa', 2048)
    const pem = await key.export("temppassword")
    const { id } = await ipfs.key.import(keyName, pem, "temppassword")
```

See this issue: ipfs/go-ipfs#7879

The relevant code is here:

https://github.com/ipfs/js-ipfs/blob/9cbc09c03ebe66a64f18f5781a801d37d9450a02/packages/ipfs-http-client/src/key/import.js#L14

**Comment by jacobheun** [comment] 2021-02-18 16:20
Duplicate of https://github.com/ipfs/js-ipfs/issues/3547

**Closed by jacobheun** 2021-02-18 16:20 UTC
