### ISSUE TITLE
Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by hunterInt** [ipfs/js-ipfs#3256] opened 2020-08-30 01:53 UTC
- **Version**: 0.48.2

- **Platform**:

Firefox 80
Brave 1.13.82
Chrome 85.0.4183.83

- **Subsystem**:

#### Description:

Once `await IPFS.create();` has run the console fills with these errors:
Firefox can’t establish a connection to the server at 
```
ws://127.0.0.1:8081/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd.
The connection to ws://127.0.0.1:8081/p2p/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64 was interrupted while the page was loading.
```

![image](https://user-images.githubusercontent.com/14793417/91648992-e2ee9000-ea2b-11ea-8b7d-115ff2ad0d1e.png)

#### Steps to reproduce the error:

```
import IPFS from 'ipfs'

await IPFS.create();
```

Or I have created and attached a simple reproduce project that will reproduce this error. 
[test.zip](https://github.com/ipfs/js-ipfs/files/5146201/test.zip)
Run it like so:
```
npm i
node server.js
```
Then visit [localhost:8080](http://localhost:8080)

**Comment by jacobheun** [comment] 2020-08-31 11:29
This isn't actually an error, but it is annoying when checking logs. The problem is that libp2p is trying to dial a websocket address that another node has advertised, but it's a private address. So when we attempt to make a websocket connection it fails. The error logged to the console is an uncatchable error due to security concerns in the browser, so there's no way for us to hide those from the logs. As long as there is another, valid public address for the peer we'll still dial and connect to it.

The feature that needs to be implemented in libp2p to mitigate the large number of errors here is multiaddr confidence, https://github.com/libp2p/js-libp2p/issues/593. This will enable us to identify `127.0.0.1:8081` as a bad IP/port combo and add it to a deny list for future dials. We can't restrict this address outright because there may indeed be a local node running on that address and port.

We will always have some of these when we receive bad addresses from another peer, but we should be able to limit the number of them with deny lists.

**Comment by jacobheun** [comment] 2020-09-03 14:16
Closing this as the underlying solution is already planned for in libp2p.

**Closed by jacobheun** 2020-09-03 14:16 UTC
Labels: need/triage

**Comment by raphael10-collab** [comment] 2021-02-01 19:46
Hi @jacobheun !
I'm having this issue too 

![image](https://user-images.githubusercontent.com/70313067/106509905-7aba4380-64ce-11eb-8668-59cacca3f7e7.png)

When is planned the solution?
