### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by ekumahost** [ipfs/js-ipfs#3620] opened 2021-04-09 11:29 UTC
My script been throwing this error no headways..
any idea

- **Version**: 47.0.1 and also the latest version

- **Platform**: Linux (google cloud)

- **Subsystem**: 

#### Description:

	
2021-04-09 12:22:05	
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2021-04-09 12:22:05	
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2021-04-09 12:22:05	
at Module.load (internal/modules/cjs/loader.js:653:32)
2021-04-09 12:22:05	
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2021-04-09 12:22:05	
at Module._compile (internal/modules/cjs/loader.js:776:30)
2021-04-09 12:22:05	
at Object.<anonymous> (/www/node_modules/multibase/src/constants.js:4:14)
2021-04-09 12:22:05	
at require (internal/modules/cjs/helpers.js:25:18)
2021-04-09 12:22:05	
at Module.require (internal/modules/cjs/loader.js:690:17)
2021-04-09 12:22:05	
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2021-04-09 12:22:05	
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2021-04-09 12:22:05	
at Module.load (internal/modules/cjs/loader.js:653:32)
2021-04-09 12:22:05	
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2021-04-09 12:22:05	
at Module._compile (internal/modules/cjs/loader.js:776:30)
2021-04-09 12:22:05	
at Object.<anonymous> (/www/node_modules/multibase/src/base.js:3:24)
2021-04-09 12:22:05	
at require (internal/modules/cjs/helpers.js:25:18)
2021-04-09 12:22:05	
at Module.require (internal/modules/cjs/loader.js:690:17)
2021-04-09 12:22:05	
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2021-04-09 12:22:05	
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2021-04-09 12:22:05	
at Module.load (internal/modules/cjs/loader.js:653:32)
2021-04-09 12:22:05	
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2021-04-09 12:22:05	
at Module._compile (internal/modules/cjs/loader.js:776:30)
2021-04-09 12:22:05	
at Object.<anonymous> (/www/node_modules/multibase/src/util.js:3:21)
2021-04-09 12:22:05	
ReferenceError: TextDecoder is not defined
2021-04-09 12:22:05	
2021-04-09 12:22:05	
^
2021-04-09 12:22:05	
const textDecoder = new TextDecoder()
2021-04-09 12:22:05	
/www/node_modules/multibase/src/util.js:3

**Comment by danielcjacks** [comment] 2021-04-09 18:13
I'm having the same issue when running the Create React App example project

**Comment by elmariachi111** [comment] 2021-04-09 20:10
Same here. Created a massively simplified CRA repo to reproduce: https://github.com/elmariachi111/ipfs-textencoder-demo

**Comment by achingbrain** [comment] 2021-04-09 20:43
What version of node are you running?

**Comment by elmariachi111** [comment] 2021-04-09 20:47
Built that with node 12.22, 14.15, 15.14 tried with yarn, npm, pnpm.

**Comment by ekumahost** [comment] 2021-04-09 20:52
> What version of node are you running?

node:10.16.0-alpine [Docker]

**Comment by elmariachi111** [comment] 2021-04-09 20:56
guess that's related to the latest multibase releases (`https://github.com/multiformats/js-multibase/compare/v4.0.2...v4.0.4`) they dropped the dependency on the generic web-encoding dependency lately: https://github.com/Gozala/web-encoding/compare/v1.1.3...v1.1.4 . Curiously, the error seems to be thrown in a multibase module @3.1.2, but the verison that ipfs-core 0.5.4 requires is definitely ^4.0.2... https://github.com/ipfs/js-ipfs/blob/74bfce3c12f743b8c1cda4b2160b25802f9f27d6/packages/ipfs-core/package.json#L114

![image](https://user-images.githubusercontent.com/1344649/114239553-84589f80-9986-11eb-99fb-a3c83268403b.png)

**Comment by achingbrain** [comment] 2021-04-09 20:59
@ekumahost please upgrade to a supported node version - 14 or 15.

@elmariachi111 you are running in a browser and likely have a different problem

**Comment by elmariachi111** [comment] 2021-04-09 23:41
it's very lkely an issue with CRA. Runs fine inside nextjs & parcel, created 2 PRs for that: https://github.com/elmariachi111/ipfs-textencoder-demo/pulls . It's quite likely that somewhen on the way CRA support broke. I just checked whether your official CRA sample (without Typescript) runs, but I found that by plainly building and running it, it shows the same error as above... (so https://github.com/ipfs/js-ipfs/tree/master/examples/browser-create-react-app is also **not** working here, node 14.15.3

**Comment by RomarQ** [comment] 2021-04-10 00:44
I have a project that is also being affected by this.

Avoid using (^) in the dependencies, it is really dangerous.

**Comment by RomarQ** [comment] 2021-04-10 01:03
A workaround, while it doesn't get fixed:
```
npm i --save web-encoding@1.1.3
```
Commit that introduced the problem: https://github.com/Gozala/web-encoding/commit/3992702cefa89e3e2f67a0b29bed41d290c5e6a8

**Comment by ekumahost** [comment] 2021-04-10 06:23
> @ekumahost please upgrade to a supported node version - 14 or 15.
> 
> @elmariachi111 you are running in a browser and likely have a different problem

I think this is going to fix the issue. trying to test and verify.

**Comment by elmariachi111** [comment] 2021-04-10 09:50
> A workaround, while it doesn't get fixed:
> 
> ```
> npm i --save web-encoding@1.1.3
> ```
> 
> Commit that introduced the problem: [Gozala/web-encoding@3992702](https://github.com/Gozala/web-encoding/commit/3992702cefa89e3e2f67a0b29bed41d290c5e6a8)

@RomarQ think it's not helping if I install web-encoding locally ;) But you know what? [When I add](https://github.com/elmariachi111/ipfs-textencoder-demo/commit/6973cadacb9bf25fa95fb9ff8f842bb9119575f4) 

```
  "resolutions": {
    "web-encoding": "1.1.3"
  },
```
to my `package.json` file, it just runs fine :) (might only work with yarn)

**Comment by ekumahost** [comment] 2021-04-11 11:34
I have upgraded node to version >14.x and issue fixed.

**Comment by katopz** [comment] 2021-05-02 12:37
I don't think so, I use node `14.16.1` but still got this issue.

![image](https://user-images.githubusercontent.com/97060/116813374-b15f3300-ab7d-11eb-86b1-d2286ee7ad27.png)

**Comment by yus1uf** [comment] 2021-09-12 08:47
I am facing the same while retrieving the data from mongodb.

**Comment by SgtPooki** [comment] 2022-07-20 20:41
@achingbrain  This is not working for me in ipfs-webui with node version 16.12.0 when I'm trying to upgrade dependencies: https://github.com/ipfs/ipfs-webui/issues/1965

**Comment by achingbrain** [comment] 2022-07-20 22:29
This may be related to your use of JSDom in the test execution: https://github.com/jsdom/jsdom/issues/2524

**Comment by SgtPooki** [comment] 2023-05-26 19:39
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

FYI, my previous issue was resolved with a jsdom global setup file.

**Closed by SgtPooki** 2023-05-26 19:39 UTC
Labels: need/triage, kind/not-helia-issue
