### ISSUE TITLE
Preload gives 200 response but 0 bytes of content for a CID

### ISSUE THREAD

**Issue by ftyers** [ipfs/js-ipfs#3859] opened 2021-09-08 15:27 UTC
- **Version**:

Object { version: "0.9.1", repo: "10", commit: "dde3d28b4a0d0f74d73c0c0b38eda2e01874a2ed", "interface-ipfs-core": "^0.148.0" }

- **Platform**:

Firefox 83.0 (64 bits)
Firefox 78.12

#### Severity:

  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:

![imatge](https://user-images.githubusercontent.com/449545/132539136-38704d06-6563-48b6-9f6d-2b3eed05143b.png)

- We tried to fetch a series of CIDs, e.g. 
  - mp3: QmfVYAvkFLorquVyTvMSnuJBniwzDArChjHoFexYPTodk2
     - https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmfVYAvkFLorquVyTvMSnuJBniwzDArChjHoFexYPTodk2
  - mp3: QmPtgmozSQXyRDggvbL4UYRPVJsofEkbDjXAiBCrbJmQDa
     - https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmPtgmozSQXyRDggvbL4UYRPVJsofEkbDjXAiBCrbJmQDa   
  - JSON: QmcEBbu8hUd5fbCsPDVc8Si6GVHQjdjmZnK17SwEm6rpgv
     - https://node1.preload.ipfs.io/api/v0/refs?r=true&arg=QmcEBbu8hUd5fbCsPDVc8Si6GVHQjdjmZnK17SwEm6rpgv
- We received 200 replies but with 0 bytes 
- We expected to receive the files

#### Steps to reproduce the error:

Go to https://demo.omnilingo.cc and try clicking on a language in the drop down on the top right, open the network tab, then switch language. The code is available [here](https://github.com/omnilingo/omnilingo/tree/main/client).

The CIDs fetch fine from `ipfs cat` on the command line.

**Comment by achingbrain** [comment] 2021-09-09 17:23
Preloading using the `/api/v0/refs` endpoint doesn't return the file contents, it causes the remote preload node to pull the content from your local node to make it more available on the IPFS network.

When I follow your instructions after a short delay I see errors in the console which may be why you aren't seeing the results you expect:

```
main.js:171 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at main.js:21
    at Array.reduce (<anonymous>)
    at fetchIpfsB (main.js:21)
    at async fetchIpfsS (main.js:27)
    at async Promise.all (/index 0)
    at async OmniLingo.fetchIndex (omnilingo.js:63)
    at async runLanguage (main.js:166)
```

The code in question is this:

```js
const chunks = []
for await (const chunk of document.ipfs.cat(cid)) {
  chunks.push(chunk)
}

const s = new Uint8Array(chunks.reduce( (acc, cur) => { acc.push(...cur); return acc }, [])); // <- the error is here
console.log("fetched: " + cid);
return s;
```

The reason being `chunks` can be `[Uint8Array(262144), Uint8Array(262144), Uint8Array(46096)]` so `acc.push(...cur)` ends up calling `acc.push` with hundreds of thousands of args which is overloading the browser.

I would suggest not doing it this way, maybe use Array.concat instead of the spread operator:

```js
const s = new Uint8Array(chunks.reduce((acc, cur) => acc.concat(cur), []));
```

or use [it-to-buffer](https://www.npmjs.com/package/it-to-buffer):

```js
import toBuffer from 'it-to-buffer'

const s = await toBuffer(document.ipfs.cat(cid))

console.log("fetched: " + cid);
return s;
```

I also sometimes see:

```
main.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at fetchIpfsB (main.js:9)
    at async fetchIpfsS (main.js:27)
    at async Promise.all (/index 0)
    at async getIndexes (main.js:107)
    at async main (main.js:180)
```

Which is:

```js
if (cid.startsWith("k5")) {
  cid_s = await fetch('https://gateway.ipfs.io/api/v0/name/resolve?arg=' + cid);
  cid_json = await cid_s.json();
  cid = cid_json["Path"];
  if(cid.startsWith("/ipfs/")) {   // <- the error is here
    cid = cid.substring("/ipfs/".length);
  }
  else {
    console.log("resolved unsupported ipfs path " + cid);
  }
}
```

In this case the gateway is failing to resolve the name but the failure is not being handled.

**Comment by achingbrain** [comment] 2022-01-12 11:43
Closing as this is working as intended.

**Closed by achingbrain** 2022-01-12 11:43 UTC
Labels: kind/support
