### ISSUE TITLE
multiaddr dependency missing

### ISSUE THREAD

**Issue by vijayee** [ipfs/js-ipfs#140] opened 2016-04-11 19:18 UTC
The 'multiaddr' module seems to be missing from the dependency list causing failure when executing 'IPFS()'. Also of note there appears to be a failing peerDependency of karma-webpack on an older version webpack.

**Comment by diasdavid** [comment] 2016-04-12 09:12
> peerDependency of karma-webpack on an older version webpack.

WebPack uses peerDependencies (unfortuantely) and so it conflicts with a older version that you might have installed globally. Do `npm uninstall webpack -g` and `npm i` again on this repo and check if it is all ok

**Comment by diasdavid** [comment] 2016-04-13 23:56
Do you still see that issue?

**Comment by vijayee** [comment] 2016-04-14 16:25
No unfortunately. Webpack was installed globally but after removal and install locally resulted in the same error message as follows.
```
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.0.7-beta does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-webpack@1.7.0 wants webpack@^1.4.0
```
the error is not critical everything seems to work anyway. However the missing 'multiaddr' stops you from  `var node = new IPFS()`

**Comment by diasdavid** [comment] 2016-04-15 06:25
We've updated the master branch to have multiaddr as a dep. 

On the Webpack issue, which npm version are you using?

**Comment by dignifiedquire** [comment] 2016-04-15 13:49
> On the Webpack issue, which npm version are you using?

it says in the error message `v2.15.0`

**Comment by diasdavid** [comment] 2016-04-15 22:44
@vijayee you will need npm 3 to work with Webpack. run `npm i -g npm`

**Comment by diasdavid** [comment] 2016-05-09 21:34
@vijayee any update here? All good?

**Comment by diasdavid** [comment] 2016-05-16 08:54
As we can't reproduce, I'm closing this one. Let us know if you run into the issue again.

**Closed by diasdavid** 2016-05-16 08:54 UTC
