### ISSUE TITLE
Google App Engine won't deploy

### ISSUE THREAD

**Issue by mrappard** [ipfs/js-ipfs#3592] opened 2021-03-15 23:14 UTC
- **Version**:0.54.2
- 
- **Platform**:Google App Engine

- **Subsystem**:NPM
#### Description:
When I deploy to the Google App Engine with

    "ipfs": "^0.54.2",
    "ipfs-only-hash": "^2.0.1",

In my package.json I get an error when building, if I remove them it builds and runs fine.

Step #6 - "builder": Running "npm ci --quiet (NODE_ENV=production)"
Step #6 - "builder": npm ERR! Error while executing:
Step #6 - "builder": npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/assemblyscript/assemblyscript.git
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! Host key verification failed.
Step #6 - "builder": npm ERR! fatal: Could not read from remote repository.
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! Please make sure you have the correct access rights
Step #6 - "builder": npm ERR! and the repository exists.
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! exited with error code: 128
Step #6 - "builder": 
Step #6 - "builder": npm ERR! A complete log of this run can be found in:
Step #6 - "builder": npm ERR!     /builder/home/.npm/_logs/2021-03-15T22_15_17_871Z-debug.log
Step #6 - "builder": Done "npm ci --quiet (NODE_ENV=production)" (12.232429128s)
Step #6 - "builder": Failure: (ID: beaf8772) npm ERR! Error while executing:
Step #6 - "builder": npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/assemblyscript/assemblyscript.git
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! Host key verification failed.
Step #6 - "builder": npm ERR! fatal: Could not read from remote repository.
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! Please make sure you have the correct access rights
Step #6 - "builder": npm ERR! and the repository exists.
Step #6 - "builder": npm ERR! 
Step #6 - "builder": npm ERR! exited with error code: 128
Step #6 - "builder": 
Step #6 - "builder": npm ERR! A complete log of this run can be found in:
Step #6 - "builder": npm ERR!     /builder/home/.npm/_logs/2021-03-15T22_15_17_871Z-debug.log
Step #6 - "builder": --------------------------------------------------------------------------------
Step #6 - "builder": Running "mv -f /builder/outputs/output-5577006791947779410 /builder/outputs/output"
Step #6 - "builder": Done "mv -f /builder/outputs/output-5577006791947779410 /builder/o..." (9.224989ms)
Step #6 - "builder": ERROR: failed to build: exit status 1
Finished Step #6 - "builder"

**Comment by achingbrain** [comment] 2021-03-22 14:36
The problem is here:

```
Step #6 - "builder": npm ERR! Error while executing:
Step #6 - "builder": npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/assemblyscript/assemblyscript.git
Step #6 - "builder": npm ERR!
Step #6 - "builder": npm ERR! Host key verification failed.
Step #6 - "builder": npm ERR! fatal: Could not read from remote repository.
```

So git is failing to make a SSL connection to github.com.  I'm closing this because it's not a problem with js-IPFS.

**Closed by achingbrain** 2021-03-22 14:36 UTC

**Comment by mrappard** [comment] 2021-03-22 14:47
It's fine to close the ticket.

But I have no ability to deal with SSL in the way I deploy to the Google App Engine (Arguably the way that everyone deploys to to the google app engine.

So yes close the issue, cause no your issue.

But update document to say "Will not run on the Google App Engine." Or arguably anything that is dependent on many of the libraries of js-IPFS.
