### ISSUE TITLE
ED25519 key generation impossible

### ISSUE THREAD

**Issue by tfoutrein** [ipfs/js-ipfs#3123] opened 2020-06-25 15:50 UTC
- **Version**:
{"version":"0.46.0","repo":7,"commit":""} 

- **Platform**:
Linux DESKTOP-21GI717 4.4.0-20150-Microsoft #1000-Microsoft Thu Jun 12 17:34:00 PST 2020 x86_64 GNU/Linux

- **Subsystem**:
KEY

#### Severity:
High

#### Description:
- What I did
const key1 = await this._node.key.gen('tata', {type : 'ed25519'})
- What happened
TypeError: keypair.export is not a function
- What you expected to happen
get the key, if i try without the type , there is no problem

#### Steps to reproduce the error:
just do  const key1 = await this._node.key.gen('tata', {type : 'ed25519'})

**Comment by achingbrain** [comment] 2020-06-25 17:01
js-ipfs doesn't support ED25519 keys yet, though support is going to land pretty soon.

Duplicate of #2553 - please see libp2p issues linked from there for further reading and timelines.

**Closed by achingbrain** 2020-06-25 17:01 UTC
Labels: need/triage
