### ISSUE TITLE
Using WebRTC with Node.js requires your machine to have a soundcard

### ISSUE THREAD

**Issue by jerry855202** [ipfs/js-ipfs#919] opened 2017-07-22 14:29 UTC
I tried to setup the included demo transfer-files on my machine today, after digging through the docs and got ipfs with wrtc setup, I run jsipfs daemon
However it wouldn't run properly and just hang if I don't interrupt it.

Here's the log
```
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/Qmxxxxxxxxxxxxxx
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/Qmxxxxxxxxxxxxxxxxx
Swarm listening on /ip4/x.x.x.x/tcp/4002/ipfs/Qmxxxxxxxxxxxxxxxxx
Swarm listening on /ip4/172.17.0.1/tcp/4002/ipfs/Qmxxxxxxxxxxxxxx
Swarm listening on /ip4/10.10.0.1/tcp/4002/ipfs/Qmxxxxxxxxxxxxxxxx
Swarm listening on /libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss/ipfs/Qmxxxxxxxxxxxxxx
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM

Received interrupt signal, shutting down..
/usr/local/lib/node_modules/ipfs/src/http-api/index.js:144
      (cb) => this.server.stop(cb),
                         ^

TypeError: Cannot read property 'stop' of undefined
    at series (/usr/local/lib/node_modules/ipfs/src/http-api/index.js:144:26)
    at /usr/local/lib/node_modules/ipfs/node_modules/async/internal/parallel.js:31:39
    at replenish (/usr/local/lib/node_modules/ipfs/node_modules/async/internal/eachOfLimit.js:64:17)
    at /usr/local/lib/node_modules/ipfs/node_modules/async/internal/eachOfLimit.js:68:9
    at eachOfLimit (/usr/local/lib/node_modules/ipfs/node_modules/async/eachOfLimit.js:39:36)
    at /usr/local/lib/node_modules/ipfs/node_modules/async/internal/doLimit.js:9:16
    at _parallel (/usr/local/lib/node_modules/ipfs/node_modules/async/internal/parallel.js:30:5)
    at series (/usr/local/lib/node_modules/ipfs/node_modules/async/series.js:83:26)
    at HttpApi.stop (/usr/local/lib/node_modules/ipfs/src/http-api/index.js:143:5)
    at process.on (/usr/local/lib/node_modules/ipfs/src/cli/commands/daemon.js:44:15)
```
After reading some similiar issues, it seems like WebRTC is somehow using ALSA
Since there's no soundcard on my machine, it seems ALSA would not work properly.

EDIT: Also tried using electron-webrtc instead of wrtc, with no luck.

**Comment by VictorBjelkholm** [comment] 2017-07-22 15:07
Would be useful to know which version of js-ipfs you're using, operating system and browser.

Seems to be a issue in wrtc that some people using Ubuntu are hitting.

**Comment by jerry855202** [comment] 2017-07-22 15:35
Currently using Ubuntu 16.04 LTS, with fresh js-ipfs pulled today from master-branch.
Browser is Firefox 54.0

**Comment by diasdavid** [comment] 2017-07-22 17:12
@jerry855202 try js-ipfs latest. It doesn't use wrtc by default and the demo is primarily for the browser, you should be able to run it without having WebRTC problems.

Interesting find though! Thank you for sharing that the issue is the lack of a sound card.

**Comment by jerry855202** [comment] 2017-07-23 13:49
@diasdavid I'm already on latest, the tutorial for transfer-files explicitly says it need WebRTC in order to work, and I already tried jsipfs init without the WebRTC Flag
The demo still won't work, with or without WebRTC.

And also, there's another problem. 
Whenever I try to use the Start IPFS button through the demo, it always puts out an error message
```
TypeError: config.Addresses is undefined
```
I don't know if it's another problem, or is it related to this. Please kindly advice, thanks in advance.

**Comment by jerry855202** [comment] 2017-07-26 14:55
@diasdavid Maybe rename the title of the issue to something like 
"js-ipfs daemon not working on machines without soundcard"
will be a more precise description to the problem here.
And it'll also makes it better for SEO.

Sidenote : I replaced the javascript source from local ( js/ipfs.js ) to unpkg solved the above mentioned TypeError problem.

So maybe the js in /js/ipfs.js is different from the unpkg one? Or it might be other problem.
Although this is unrelated to soundcard issue, it's still an example related issue so I kept it here.

**Comment by diasdavid** [comment] 2017-09-01 13:25
This issue is with [wrtc](https://www.npmjs.com/package/wrtc) module itself and not js-ipfs. 

You can also use electron-webrtc. Unfortunately, I can't vet for any of the two as solid solutions. Read more here https://github.com/ipfs/js-ipfs#is-there-webrtc-support-for-js-ipfs-with-nodejs

Closing this issue for now as webrtc in Node.js was removed by default to avoid these situations

**Closed by diasdavid** 2017-09-01 13:25 UTC
Labels: backlog, bug, P3 - Low
