### ISSUE TITLE
ipfs.get is not working with sharded directories

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#1279] opened 2018-03-23 22:57 UTC
- **Version**: 0.28.2
- **Platform**: Mac OS X
- **Subsystem**: unixfs-engine

#### Description:

When fetching a directory using ipfs.get (or jsipfs get), it fails with the following error:

```
» jsipfs get QmXNHWdf9qr7A67FZQTFVb6Nr1Vfp4Ct3HXLgthGG61qy1
Saving file(s) QmXNHWdf9qr7A67FZQTFVb6Nr1Vfp4Ct3HXLgthGG61qy1
/Users/tmp/code/js-ipfs/src/cli/commands/files/get.js:67
      if (err) { throw err }
                 ^

Error: invalid node type
    at parseError (/Users/tmp/code/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/Users/tmp/code/js-ipfs/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:548:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
```

#### Steps to reproduce the error:

```
# start one daemon in one terminal
jsipfs daemon
# fetch in another terminal
jsipfs get QmXNHWdf9qr7A67FZQTFVb6Nr1Vfp4Ct3HXLgthGG61qy1
```

**Comment by diasdavid** [comment] 2018-03-23 22:57
go-ipfs has the same issue -- https://github.com/ipfs/go-ipfs/issues/4871 --. For some reason this went uncaught for a while.

**Comment by diasdavid** [comment] 2018-07-29 09:49
@achingbrain did you happen to make a fix for this when you implemented mfs and touched unixfs-engine?

**Comment by lidel** [comment] 2018-08-15 19:25
### Problem

I've just stumbled upon this bug while working on https://github.com/ipfs-shipyard/ipfs-companion/pull/533. 

Tried running embedded js-ipfs node as the protocol handler backend, but it fails to load Turkish wikipedia mirror: `/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Anasayfa.html` where `/wiki/` is `hamt-sharded-directory`. 

What is interesting, our public gateways and local go-ipfs v4.0.17 [load it without any problem](https://ipfs.io/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Anasayfa.html), which implies support for resolving unixfs paths over HAMT sharded tree is possible.

### How to Reproduce

Minimal repro of ipfs-companion use is basically this:

```js
let cat = ipfs.files.catReadableStream('/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Anasayfa.html');
cat.on('data', (chunk) => {console.log(`Received ${chunk.length} bytes of data.`);});
cat.on('error', (err) => {console.log('catReadableStream produced error', err);});
cat.on('end', () => {console.log('There will be no more data.');});
cat.resume();
```

If you execute it, nothing will happen for a long time, but in the background  [`js-ipfs-unixfs-engine:src/exporter/resolve.js`](https://github.com/ipfs/js-ipfs-unixfs-engine/blob/c5cb38b092f9aa3fcc891075377636e8ac4699c5/src/exporter/resolve.js#L54) becomes a hot path resolving `/wiki/` over and over again until it hits a raw node such as [/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/I/favicon.png](https://ipfs.io/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/I/favicon.png) and [`src/exporter/object.js`](https://github.com/ipfs/js-ipfs-unixfs-engine/blob/c5cb38b092f9aa3fcc891075377636e8ac4699c5/src/exporter/object.js#L8) throws `invalid node type` due to `pathRest` being empty.

Not sure where to go from there, but I  hope the above notes save some initial debug time.

**Comment by SgtPooki** [comment] 2023-05-26 18:46
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!

**Closed by SgtPooki** 2023-05-26 18:46 UTC
Labels: kind/bug, exp/wizard, status/ready, P1
