### ISSUE TITLE
Browser-Create-React-App example fails

### ISSUE THREAD

**Issue by raphael10-collab** [ipfs/js-ipfs#3415] opened 2020-11-21 11:40 UTC
After executing the commands yarn -> yarn start I get these errors:

![image](https://user-images.githubusercontent.com/70313067/99876384-9e236100-2bf6-11eb-822f-edd5e3318e7b.png)

Ubuntu 18.04.4 Desktop

**Comment by achingbrain** [comment] 2020-11-26 16:12
Possibly a duplicate of https://github.com/ipfs/js-ipfs/issues/1388

Are you running in a private browser window?

**Comment by lidel** [comment] 2021-05-24 14:46
Closing as stale, feel free to reopen if the problem is still present in the latest version.

**Closed by lidel** 2021-05-24 14:46 UTC
Labels: kind/support, need/author-input
