### ISSUE TITLE
Node failed to start! Error: Not able to start from state: running

### ISSUE THREAD

**Issue by bgits** [ipfs/js-ipfs#1880] opened 2019-02-14 21:00 UTC
```
const ipfs = new IPFS()

ipfs.on('ready', () => {
  console.log('Node is ready to use!')

  ipfs.start(error => {
    if (error) {
      return console.error('Node failed to start!', error)
    }
    console.log('Node started!')
  })

  ipfs.swarm.peers(function (err, peerInfos) {
    if (err) {
      throw err
    }
    console.log(peerInfos)
  })

  ipfs.swarm.addrs(function (err, addrs) {
    if (err) {
      throw err
    }
    console.log({addrs})
  })

  const validCID = 'QmY8hBsESwuTRSWUh7iMYVKhyVTpt8kacQSFPWRuf8r1iT'

  ipfs.get(validCID, function (err, files) {
    files.forEach((file) => {
      console.log(file.path)
      console.log(file.content.toString('utf8'))
    })
  })

  ipfs.version((err, version) => { console.log({version})})
})

```

#### Description:

ipfs.start throws the error and does not log out:"Node Started'

error: ipfs.js:14 Node failed to start! Error: Not able to start from state: running

Uncaught Error: Not able to start from state: running

It returns no peers but does return 8 addrs. It is not able to get the CID.

#### Steps to reproduce the error:

I would have that code run on page load in the browser.

**Comment by ethericsol** [comment] 2019-02-14 22:38
I could be wrong but I think you don't need ipfs.start. I think when you create the ipfs instance it defaults to start.

**Comment by bgits** [comment] 2019-02-15 00:03
> I could be wrong but I think you don't need ipfs.start(). I believe when you create the ipfs instance it defaults to start.

Perhaps but the problem is still there in being unable to retrieve content.

**Comment by ethericsol** [comment] 2019-02-15 00:14
Yes.  I believe it is caused by the same issue I submitted here https://github.com/ipfs/js-ipfs/issues/1874

**Comment by alanshaw** [comment] 2019-02-15 11:44
@bgits yes @ethericsol is correct, you do not need to call `start` unless you explicitly don't start the node by passing `start: false` to the constructor.

Not being able to fetch content is a dupe of https://github.com/ipfs/js-ipfs/issues/1874

**Closed by alanshaw** 2019-02-15 11:44 UTC
