### ISSUE TITLE
[ipfs-core] - Exception is raised when attempting to releaseLock

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/js-ipfs#3520] opened 2021-02-03 07:05 UTC
### Environment
- Debian Bullseye, Kernel 5.10.12-xanmod1
- Chrome Version 88.0.4324.146 (Official Build) (64-bit)
- ipfs-core 0.5.1

#### Severity:
Medium, while debugging Chrome always complain even the 'Pause on caught exceptions' is unchecked

#### Description:
ipfs-http-client dynamically downloaded from jsdelivr
https://cdn.jsdelivr.net/npm/ipfs-http-client@49.0.1/dist/index.min.js

### Component
ipfs-core/src/runtime/preload-brower.js

Chrome Developper tools is open.
The following exception is triggered in the finally close while attempting to release the reader lock (line 32)

TypeError: This readable stream reader has been released and cannot be used to monitor the stream's state

Thanks

**Comment by achingbrain** [comment] 2021-02-08 15:03
Do you have a small example project I can use to reproduce this problem?

**Comment by xmaysonnave** [comment] 2021-02-09 03:48
@achingbrain I will be very happy to provide an example however :
I dynamically load the library from jsdelivr (sri hash enabled) I noticed that no non minified version is available. 
https://www.jsdelivr.com/package/npm/ipfs-http-client?path=dist
It would be useful to have a non minified version available. 
Maybe if you can build a non minified version  on github I will able to load itwith a minimal impact on my side.
The idea here is to reproduce it on my side and give you something useful.
Let me know.
Thanks

**Comment by achingbrain** [comment] 2021-02-09 10:27
Linking to the minified code in your project is fine, I can always swap it out locally to see if the error still occurs.

**Comment by xmaysonnave** [comment] 2021-02-10 07:23
Chrome Version 88.0.4324.150 (Official Build) (64-bit)
Debian Bullseye, kernel 5.10.14-xanmod1

https://dweb.link/ipfs/bafybeiguy3u45vc2i5ojlhmqfffpvxpfrcs4nq7ov6ez7kj7vbzmfuvx4m

Load IPFS with TiddlyWiki with the previous link.
Open the Developer Tools (ipfs-http-client is not yet loaded).
Select Sources and open the console. 
I usually preserve the console log while saving.
The pause on caught exceptions is unchecked.

At the very top:
- add a tiddler (+ command),
- save it (green button),
- the wiki should be dirty (At the very top you should see the save button who turned red)

You are going to save over ipfs.infura.io:5001 and load the new wiki from dweb.link.
The console will output a lot of informations.

While saving the exception is raised multiple times.

Thanks

**Comment by achingbrain** [comment] 2021-02-24 14:19
Do I need to be authenticated at all?  I've followed your instructions but get a 403 when it tries to do an `ipfs.files.stat`:

![image](https://user-images.githubusercontent.com/665810/109013590-41c75600-76ab-11eb-8132-9db76764a054.png)

**Comment by xmaysonnave** [comment] 2021-02-24 14:35
This exception is raised and catched as infura do not allow files.stat. The
program flow should not be disturbed. No authentication is required. Did
you get the exception I detailed? Thanks

**Comment by achingbrain** [comment] 2021-02-24 14:59
> infura do not allow files.stat.

It looks like the application is invoking this here: https://github.com/xmaysonnave/tiddlywiki-ipfs/blob/73038b5b41d1675848a978207f4b53c3f1c2a316/core/modules/library/ipfs-bundle/ipfs-library.js#L372 called from here: https://github.com/xmaysonnave/tiddlywiki-ipfs/blob/73038b5b41d1675848a978207f4b53c3f1c2a316/core/modules/library/ipfs-bundle.js#L426

You may need to refactor your application to only use APIs that infura allow.

> Did you get the exception I detailed?

No, only what I pasted above.

**Comment by xmaysonnave** [comment] 2021-05-30 06:51
The exception remains in the latest however with Chrome Developer Tools the 'Pause on Exceptions' should be selected (the 'Pause on caught exception' should be unchecked)

![ksnip_20210530-121633](https://user-images.githubusercontent.com/20576132/120095005-18521680-c141-11eb-9877-dea0ce309af1.png)

This exception is handled by Chrome though and do not seem to cause any trouble if Pause on Exceptions is unchecked.

Thanks

**Comment by SgtPooki** [comment] 2023-05-26 20:13
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in kubo-rpc-client that should work much better.

**Closed by SgtPooki** 2023-05-26 20:13 UTC
Labels: kind/support
