### ISSUE TITLE
interface-ipfs-core tests failing on my machine

### ISSUE THREAD

**Issue by kumavis** [ipfs/js-ipfs#902] opened 2017-07-07 08:27 UTC
on a fresh clone of master
```
  52 passing (3m)
  2 pending
  3 failing

  1) interface-ipfs-core tests .files callback API .add BIG buffer:
     Error: Uncaught AssertionError: expected [] to have a length of 1 but got 0 (webpack:///~/chai/lib/chai/assertion.js?fee1:141:0 <- test/core/interface/interface.spec.js:152161)

  

  2) interface-ipfs-core tests .files callback API .add .createAddStream stream of valid files and dirs:
     Error: Uncaught AssertionError: expected 'QmZf3drqiuCuuCZKSmvhVRV6GH4QuJj7Gwy1QEacRMKLfy' to equal 'QmVvjDy7yF7hdnqE8Hrf4MHo5ABDtb5AbX6hWbD3Y42bXP' (webpack:///~/chai/lib/chai/assertion.js?fee1:141:0 <- test/core/interface/interface.spec.js:152161)

  

  3) interface-ipfs-core tests .files callback API .cat streams a large file:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by kumavis** [comment] 2017-07-07 18:47
my system setup is a bit nonstandard
im running qubes (which forwards traffic through a few vms) and have a vpn
not sure if this will affect it

**Comment by diasdavid** [comment] 2017-07-09 14:42
It's hard for me to see what's going on without having a way to replicate the environment. 

The files API should not fail and since WebRTC is not injected by default anymore, there shouldn't be anything that could cause a lag on the network side of things that would trickle lagging to those tests. 

The first two tests seem like a Race condition to me (//cc @pgte) and the third one fails because the other two didn't finish correctly.

**Comment by pgte** [comment] 2017-07-10 09:12
@kumavis can't seam to reproduce this in any way...
Is this failure consistent?

**Comment by kumavis** [comment] 2017-07-13 19:00
yeah consistent on re-runs
```
user@work  ~/dev/js-ipfs   master 
 ⧖  npm -v
4.6.1

 user@work  ~/dev/js-ipfs   master 
 ⧖  node -v
v8.1.3
```

just pull down latest (after 0.25 release) and got a new error added to the set

```
  123 passing (3m)
  8 pending
  4 failing

  1) interface-ipfs-core tests .files callback API .add BIG buffer:
     Error: Uncaught AssertionError: expected [] to have a length of 1 but got 0 (webpack:///~/chai/lib/chai/assertion.js?fee1:141:0 <- test/core/interface/interface.spec.js:123057)

  

  2) interface-ipfs-core tests .files callback API .add .createAddStream stream of valid files and dirs:
     Error: Uncaught AssertionError: expected 'QmZf3drqiuCuuCZKSmvhVRV6GH4QuJj7Gwy1QEacRMKLfy' to equal 'QmVvjDy7yF7hdnqE8Hrf4MHo5ABDtb5AbX6hWbD3Y42bXP' (webpack:///~/chai/lib/chai/assertion.js?fee1:141:0 <- test/core/interface/interface.spec.js:123057)

  

  3) interface-ipfs-core tests .files callback API .cat streams a large file:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  

  4) interface-ipfs-core tests .files callback API .get large file:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
these failures are all on 'test:karma-raw'

so maybe some issue with browser comms?

**Comment by diasdavid** [comment] 2017-09-01 13:26
@kumavis closing this one. If you manage to replicate this issue for us, I'm happy to reopen and tackle it :)

**Closed by diasdavid** 2017-09-01 13:26 UTC
Labels: backlog, bug, P4 - Very Low
