### ISSUE TITLE
ipfs add -r --only hash dir output hash doesn't match ipfs.add(etc etc output hash

### ISSUE THREAD

**Issue by SaulMoonves** [ipfs/js-ipfs#4083] opened 2022-04-13 17:26 UTC
- **Version**:
ipfs-core version: 0.14.2
ipfs cli version: 0.10.0

- **Platform**:
Linux deathstar 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

#### Severity:
Low

#### Description:
Created a directory with one file in it, and attempted to recursively add the directory. 
ipfs-core gives a different CID for the directory than ipfs command line tool.

```
import * as IPFS from "ipfs-core";

const ipfs = await IPFS.create();

const addResults = await ipfs.add({
    path: "./build/ipfs/media-test",
    recursive: true,
    onlyHash: true
});

const out = JSON.stringify(addResults, null, 4);
console.log(out);
```
using cli:
```
ipfs add -r --only-hash ./build/ipfs/media-test
```

I expected these to match. cli is: QmWbwGegf21hNF1uWv9GRSswN2CoYVKDq9mW5av1ANeNJp
ipfs-core is: QmTAtWFv3V9vVucGiunF4gfoQqVcyjSK9Fp6jkJxW336CT

Here is my test file: [banana.txt](https://github.com/ipfs/js-ipfs/files/8483419/banana.txt)

halp

**Comment by lidel** [comment] 2022-04-22 14:23
@SaulMoonves seems you are using  older versions of both go-ipfs and js-ipfs – mind trying with the latest versions and confirming the issue is still present?

**Comment by BigLep** [comment] 2022-05-06 14:23
Closing due to missing information.  Please reopen if this is still an issue with the latest versions.

**Closed by BigLep** 2022-05-06 14:23 UTC
Labels: need/author-input
