### ISSUE TITLE
IPFS node.on('start') not working correctly in Chrome 

### ISSUE THREAD

**Issue by EthanHaley** [ipfs/js-ipfs#915] opened 2017-07-18 19:25 UTC
I'm currently trying to run some of the examples available for IPFS, however the IPFS nodes don't seem to properly start in Chrome. I've tried both the transfer-files from this repo and the collaborative editing demo (https://github.com/ipfs-shipyard/shared-editing-demo) and in both cases the nodes start and demos work in Firefox, however trying to load them in Chrome produces no results. For transfer-files it just hangs on start, and the collaborative editing just leaves you typing in your own little text area in Chrome. Firefox nodes properly talk to each other and function as expected, however Chrome nodes don't talk to other Chrome nodes or Firefox nodes. It seems like a bug coming from Chrome but I'm not sure what is causing it exactly. Any information to help with this would be greatly appreciated.

**Comment by VictorBjelkholm** [comment] 2017-07-18 19:27
Could you put a reproducible snippet here so we can try out? Also, listen for any errors and console.log them, include them here if they appear.

**Comment by EthanHaley** [comment] 2017-07-18 19:45
![collabediting](https://user-images.githubusercontent.com/1121427/28336395-6482d64e-6bc7-11e7-80c7-0093d951fa6c.png)
![transfer-files](https://user-images.githubusercontent.com/1121427/28336396-64861ed0-6bc7-11e7-8cdf-1d35226b0371.png)

This the code I am running. No errors are thrown. I have the console.log in the transfer to see if the code is hitting node.on('start'). All messages are output in Firefox, while just the first two console.log are outputted in Chrome, which is why I believe it to be an issue in node('start') on Chrome.

**Comment by EthanHaley** [comment] 2017-07-18 20:18
![errors](https://user-images.githubusercontent.com/1121427/28337781-5ee40b4a-6bcc-11e7-9d04-a38c500f05de.png)

**Comment by VictorBjelkholm** [comment] 2017-07-18 21:20
So `DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)` seems to be the error that is being thrown here. 

Short URL leads to: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

But I'm not sure what feature in js-ipfs or yjs / y-ipfs-connector that triggers this. From what URL are you running your example? Localhost?

**Comment by EthanHaley** [comment] 2017-07-18 21:25
I am running my example from a server that I am accessing via SSH. I added the IP address of the server to the gateway portion of the IPFS config in addition to localhost.

**Comment by kareniel** [comment] 2017-07-27 02:20
I ran into this issue just now. Worked fine on Firefox, but not on Chrome.
Turned out my development server (`budo`) served content at my machine's local IP by default (something like 192.168.0.100), while go-ipfs uses 127.0.0.1 for it's http endpoint. 
I configured `budo` to serve from 127.0.0.1 instead and got it to work.

I think that Chrome considers your IPFS node's endpoint to be an insecure origin. `http-server` seems to be the dev server you're using, and I think it uses 0.0.0.0 as a default host address.You can use the `-a` option to pass it a different address.

**Comment by diasdavid** [comment] 2017-08-26 13:16
Thanks for the precious insight @kareniel :)

@EthanHaley still hitting this issue?

**Comment by diasdavid** [comment] 2017-09-12 08:54
@EthanHaley closing, let us know if you still see this problem.

**Closed by diasdavid** 2017-09-12 08:54 UTC
Labels: bug, question, ready
