### ISSUE TITLE
ipfs

### ISSUE THREAD

**Issue by jordan-public** [ipfs/js-ipfs#3601] opened 2021-03-30 20:20 UTC
- **Version**:
0.54.4

- **Platform**:
Darwin internal2.bitola.com 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

- **Subsystem**:
js-ipfs: ipfs.files.write

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
File upload / write truncates to 262144 when file is larger.

#### Steps to reproduce the error:
Use sample "browser-mfs" from "examples". Run it.
Drop any file larger than 262144 in the browser window. I used a 863KB file to upload.
The uploaded file is truncated to 262144.

**Comment by achingbrain** [comment] 2021-04-01 11:00
May be a duplicate of #3576

**Comment by scenaristeur** [comment] 2022-11-17 02:30
any news on this issue ?

**Closed** 2022-11-17 19:20 UTC
Labels: need/analysis
