### ISSUE TITLE
ipfs.get gets stuck for longer than a minute

### ISSUE THREAD

**Issue by comntr** [ipfs/js-ipfs#1882] opened 2019-02-18 09:28 UTC
Hello,

I've been trying to resolve the following ipfs dir with `ipfs.get`, but with no success so far:

```
QmYGw1DiYo94kfSKGQfC83Jxt7w54gnuwoyBre2x3Wz3pc
```

The `ipfs.io/ipfs/...` gateway resolves the id instantly.

`ipfs.get` works with some popular ids, but not with this one.

Sample code:

https://github.com/comntr/client/blob/922eb68502fb14cc692ac39f685b8d137d6d8690/index.js#L25

Does it print logs somewhere so I could attach them to the bug?

**Comment by alanshaw** [comment] 2019-02-18 13:04
dupe of https://github.com/ipfs/js-ipfs/issues/1874

**Closed** 2019-02-19 02:26 UTC
