### ISSUE TITLE
Pubsub doesn't work in different browsers if they use the same repo name

### ISSUE THREAD

**Issue by gfpacheco** [ipfs/js-ipfs#3157] opened 2020-07-08 18:41 UTC
- **Version**:
`{version: "0.47.0", repo: 7, commit: ""}`

- **Platform**:
Mac OS 10.15.5
Chrome 83.0.4103.116
Firefox 78.0.1

#### Severity:
High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
Serving the [exchange-files-in-browser](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser) and opening http://127.0.0.1:12345/ in both Chrome and Firefox works just fine.

But since I'm working on a browser extension I would like to keep the same `repo` name across browser sessions, instead of using a [random one](https://github.com/ipfs/js-ipfs/blob/master/examples/exchange-files-in-browser/public/app.js#L50) every time.

Except the pubsub feature stops working as soon as I do that, I understand that it wouldn't work if you open multiple tabs on the same browser, maybe because they would be using the same IndexedDB or whatever. But I'm opening one tab on each browser, and the only thing I removed was the random part of the repo name. After that one browser never receives the messages from the other one.

And why would the repo name have anything to do with it?

#### Steps to reproduce the error:
- Clone the [exchange-files-in-browser](https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser) example.
- Remove the ` + Math.random()` from the [repo name](https://github.com/ipfs/js-ipfs/blob/master/examples/exchange-files-in-browser/public/app.js#L50).
- Run `npm run dev` (not `npm start`)
- Open the app (http://127.0.0.1:12345/) in different browsers and try to send files from one to another.

**Comment by achingbrain** [comment] 2020-07-09 09:29
I'm having problems replicating this.  It works for me with 1x Chrome window and 1x Firefox window running at the same time.

As I think you've worked out it won't work with 2x Chrome windows (for example) as they'll share the repo and as such the peer ID so each node will ignore pubsub messages it think it's sent itself.

FWIW I had to turn off 'shields up' on Brave due to `RTCPeerConnection.createOffer` resolving an undefined value- similar to what's described at https://github.com/webrtcHacks/adapter/issues/1028 (though I don't think that module is used anywhere in the stack).

**Comment by gfpacheco** [comment] 2020-07-09 14:15
That is weird, it doesn't for me, not on Chrome/Firefox/Safari/Edge.

Are you sure you re-built the example after removing the random part of the repo name?

Can you tell me the exact steps you took?

**Comment by jacobheun** [comment] 2020-07-16 14:46
Can you send a screencast of the issue as we aren't able to reproduce?

**Comment by jacobheun** [comment] 2020-07-23 14:17
@gfpacheco if you're still having this issue and can provide a screencast of the issue that would be helpful. Going to close this for now, but we can reopen if we get reproducible steps.

**Closed by jacobheun** 2020-07-23 14:17 UTC
Labels: need/analysis, need/author-input

**Comment by gfpacheco** [comment] 2020-07-23 14:51
I moved back to using `libp2p` directly, I'm not sure that's still an issue, you can keep it closed
