### ISSUE TITLE
files.cat(cid.buffer) throws error: multihash length inconsistent

### ISSUE THREAD

**Issue by realharry** [ipfs/js-ipfs#1247] opened 2018-03-05 07:40 UTC
- **Version**: 0.28.0
- **Platform**: Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linu
- **Subsystem**: Node.js v6.11.5

#### Description:

Not sure if I'm using the API correctly, but this is what I do:

(1) Create a buffer from a string content.
(2) Add a file using the buffer to an IPFS node.
(3) Create a CID with the buffer content (with version==1).
(4) Fetch the content using the API, `files.cat(cid.buffer)`.

It throws the following exception:

    Error: multihash length inconsistent: 0x122017babbbb5ec8d6ec709a5fd1b559d0126cf36486145f84f9c39260ae0d87ab7e
        at Object.decode (/home/harry/js-ipfs/node_modules/multihashes/src/index.js:99:11)
        at Object.validate (/home/harry/js-ipfs/node_modules/multihashes/src/index.js:210:11)
        at Function.validateCID (/home/harry/js-ipfs/node_modules/cids/src/index.js:254:8)
        at new CID (/home/harry/js-ipfs/node_modules/cids/src/index.js:104:9)
        at pathBaseAndRest (/home/harry/js-ipfs/node_modules/ipfs-unixfs-engine/src/exporter/index.js:30:15)
        at module.exports.err (/home/harry/js-ipfs/node_modules/ipfs-unixfs-engine/src/exporter/index.js:47:13)
        at _catPullStream (/home/harry/js-ipfs/src/core/components/files.js:142:7)
        at Function.cat.promisify (/home/harry/js-ipfs/src/core/components/files.js:234:9)
        at Object.cat (/home/harry/js-ipfs/node_modules/promisify-es6/index.js:32:27)
        at Timeout.setTimeout (/home/harry/js-ipfs/test/core/files-cat.spec.js:82:18)
        at ontimeout (timers.js:386:11)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)

#### Steps to reproduce the error:

Code snippets:

      let buffer = Buffer.from(content);
      let mh = multihashing(buffer, 'sha2-256')
      let cid = new CID(1, 'dag-cbor', mh)
      ipfs.files.add(buffer, {}, (err, filesAdded) => {
        path = filesAdded[0].path;
        console.log("Created: path = " + path)
      })
      // ...
      ipfs.files.cat(cid.buffer, (err, data) => {
        console.log(err)
        console.log(data)
      })

**Comment by realharry** [comment] 2018-03-05 07:47
Just to be clear, `files.cat()` works in my sample/test code if I pass in the path (or, multihash) param.

**Comment by realharry** [comment] 2018-03-05 08:08
I cannot `files.get()` or `files.cat()` with `ipfsPath = cid.toBaseEncodedString()` either. They do not throw an error, but these methods do not return.

**Comment by diasdavid** [comment] 2018-03-06 12:14
Same issue as https://github.com/ipfs/js-ipfs/issues/1229

**Comment by brockmiller** [comment] 2018-03-16 23:56
Hi @diasdavid, I started looking into this issue (along with #1229, which you stated was the same issue), and I'm a little stumped on why they are actually the same issue?  

According to this bug report, it looks like he is in fact correctly supplying a CID of type Buffer (cid.buffer), and the issue seems to be due to inconsistent hash length.  My best guess is that there is some inconsistency or misuse in how he is generating his multihash and CID (steps 1-4 in the description).

However, on #1229, the issue is slightly different in that he is actually supplying a formal CID object, which the normalizePath function does not handle.  The resolution to that problem seems to just require an enhancement of the normalizePath method so that it can convert the CID into a b58 string.

I'm looking to tackle one of these issues as my first contribution to the project, so I just want to make sure I'm looking at these issues correctly.  Thoughts?  Thanks!

**Comment by mitra42** [comment] 2018-03-17 04:01
@brockmiller - that's correct about #1229 - the issue was that we were previously supplying a cid object to the function and it worked, and that stopped working.  I think I've caught all the instances in my code, but I'm guessing other people's (previously working) code might also break.

**Comment by vasco-santos** [comment] 2018-04-16 16:06
I analyzed this issue, but I could not reach a successful case.

At first, the mentioned error: `multihash length inconsistent: 0x122017babbbb5ec8d6ec709a5fd1b559d0126cf36486145f84f9c39260ae0d87ab7e`

This occurs because of being used `cidVersion = 1` for `cat`, while the default version is 0.

Using the following code:

```js
    const content = 'Multiaddrs are cool.'
    const buffer = api.Buffer.from(content)

    ipfs.files.add(buffer, {}, (err, filesAdded) => {
      const path = filesAdded[0].path
      const cidCorrect = new node.types.CID(path)

      console.log('cid', cidCorrect, cidCorrect.buffer);

    })
``` 

If we analyze the CID obtained using the received path, besides version 1 being used, it is also being used `dag-pb`, instead of `dag-cbor`.

Despite all this, I still trying to understand one problem, which happens in this case.

```js
const buffer = api.Buffer.from(content)
const mh = multihashing(buffer, 'sha2-256')
const cid = new node.types.CID(0, 'dag-pb', mh)
```

The obtained CID is different than the obtained previously on `cidCorrect`. Basically, the `multihash` value is different from the used in the `ipfs.files.add`. As a consequence, an empty response is received in the `ipfs.files.cat`. If I use cat with the `cidCorrect` or `cidCorrect.buffer`, the `'Multiaddrs are cool.'` string is received

**Comment by alanshaw** [comment] 2019-03-12 09:58
Closing this as I believe it has been resolved. I can see that `ipfs.cat` supports buffers as the `normalizePath` function detects them here https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files-regular/utils.js#L6 Please open an new issue if this is seen again! Thank you.

**Closed by alanshaw** 2019-03-12 09:58 UTC
Labels: P1 - High, bug, difficulty:easy, help wanted, ready
