### ISSUE TITLE
don't throw error when connect failure

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs#1649] opened 2018-10-21 10:52 UTC
in browser,an error thrown when it can't be connect.
i think the error should not be thrown.
in p2p network ,connecting failure is normal and many nodes can not be connect in fact.

**Comment by alanshaw** [comment] 2018-10-31 15:51
Closing this as a duplicate of #1326

**Closed by alanshaw** 2018-10-31 15:51 UTC
Labels: duplicate
