### ISSUE TITLE
Exception in Electron production package 

### ISSUE THREAD

**Issue by pruflyos** [ipfs/js-ipfs#2374] opened 2019-08-20 19:51 UTC
- **Version**: 0.37.0
- **Platform**: Electron 6.0.0, Ubuntu 18.04 (x86_64)
- **Subsystem**: ipfs-mfs

#### Description:
When packaging the Electron app into an AppImage an running it the following exception is thrown at the line when the node is created via `const node = await IPFS.create()`:

```
TypeError: Queue is not a constructor
    at createMutex (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/mortice/lib/index.js:18:23)
    at module.exports (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/mortice/lib/index.js:106:21)
    at module.exports (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/ipfs-mfs/src/core/utils/create-lock.js:12:17)
    at module.exports (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/ipfs-mfs/src/core/index.js:71:16)
    at Object.module.exports [as filesMFS] (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/ipfs/src/core/components/files-mfs.js:28:19)
    at new IPFS (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/ipfs/src/core/index.js:111:29)
    at Function.module.exports.create (/tmp/.mount_electrCHCd44/resources/app.asar/node_modules/ipfs/src/core/index.js:180:10)
    at App.<anonymous> (/tmp/.mount_electrCHCd44/resources/app.asar/background.js:33:94330)
    at App.emit (events.js:205:15)
```

This exception is not thrown in development mode when running via `yarn run electron:serve`.

#### Steps to reproduce the error:
See instructions at https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/416
and run `yarn run electron:build` and run the `.AppImage` in the `dist_electron` subfolder.

**Comment by achingbrain** [comment] 2019-08-21 09:21
Can you confirm which version of [`p-queue`](https://www.npmjs.com/package/p-queue) is in your bundle?  It looks like the default export changed between `v5` and `v6`.

**Comment by pruflyos** [comment] 2019-08-21 21:10
In app.asar, if I unpack it:

```
{
  "name": "p-queue",
  "version": "6.1.1",
...
}
```

**Comment by achingbrain** [comment] 2019-08-22 09:08
Is there no other version in there?  [`mortice`](https://www.npmjs.com/package/mortice), where the error is being thrown from, [depends on `p-queue@^5.0.0`](https://github.com/achingbrain/mortice/blob/master/package.json#L44) so it's not going to work if only `v6` is present.

It can be updated to require `v6` instead, but if your build process is flattening the dependency tree and consequently including incompatible versions you're probably going to have other problems.

**Comment by achingbrain** [comment] 2019-08-22 15:59
Mortice now depends on v6 which should help, please open an issue on the [mortice repo](https://github.com/achingbrain/mortice) if you continue to have problems.

**Comment by pruflyos** [comment] 2019-09-07 13:47
Upgraded to ipfs ` 0.37.1` but the issue seems to be with `libp2p-kad-dht@~0.15.3`. Here are the dependencies from `yarn list`:

```
├─ ipfs@0.37.1
│  ├─ libp2p-kad-dht@~0.15.3
├─ libp2p-kad-dht@0.15.3
│  ├─ p-queue@^5.0.0
│  ├─ p-queue@5.0.0
│  │  └─ eventemitter3@^3.1.0
```

This means that `libp2p-kad-dht` is currently holding off `p-queue` v6 from being bundled in the final app.asar.

**Comment by mboperator** [comment] 2019-10-21 02:56
I'm getting this same issue 

@achingbrain can we reopen this?

**Comment by alanshaw** [comment] 2019-10-21 10:43
Thanks for the PR @mboperator - re-opening this until https://github.com/libp2p/js-libp2p-kad-dht/pull/146 gets merged and released.

**Comment by mboperator** [comment] 2019-10-27 22:38
Confirmed that this bug isn't fixed with `ipfs@0.39.0`
It's due to `ipfs-repo` relying on `p-queue@^5.0.0`

I've confirmed that the error in this issue goes away with the pull request linked above.

Unfortunately, another error related to `p-queue` and `p-timeout` occurs.

**Closed** 2019-10-30 16:54 UTC
Labels: bug, difficulty:easy, in progress, libp2p

**Comment by mboperator** [comment] 2019-11-01 21:32
Update:
I've confirmed that the previously mentioned issue with `p-queue` and `p-timeout` no longer occurs.

#2574 Fixes ipfs in Electron 😄
Thanks for creating `js-ipfs`!

**Comment by momack2** [comment] 2019-11-05 22:09
Woohoo! Thanks for tracking this down and getting it fixed @mboperator!!
